### ISSUE TITLE
Sample set permissions issue

### ISSUE THREAD

**Issue by jayrbolton** [kbase/index_runner#148]
@slebras I'm seeing the following auth error on the index runner in CI:

```
8/5/2020 11:37:16 AM2020-08-05 18:37:16 ERROR    Error processing message: RuntimeError Returned from sample service with status 500 - {"error": {"code": -32000, "name": "Server error", "message": "Sample service error code 20000 Unauthorized: User jayrbolton cannot read sample cf679098-f431-4960-853f-d5df0590566f", "error": "Traceback (most recent call last):\n  File \"/kb/module/lib/SampleService/SampleServiceServer.py\", line 102, in _call_method\n    result = method(ctx, *params)\n  File \"/kb/module/lib/SampleService/SampleServiceImpl.py\", line 299, in get_sample\n    id_, _get_user_from_object(ctx, _CTX_USER), ver, as_admin=admin)\n  File \"/kb/module/lib/SampleService/core/samples.py\", line 179, in get_sample\n    self._check_perms(_not_falsy(id_, 'id_'), user, _SampleAccessType.READ, as_admin=as_admin)\n  File \"/kb/module/lib/SampleService/core/samples.py\", line 140, in _check_perms\n    raise _UnauthorizedError(errmsg)\nSampleService.core.errors.UnauthorizedError: Sample service error code 20000 Unauthorized: User jayrbolton cannot read sample cf679098-f431-4960-853f-d5df0590566f\n"}, "id": "", "version": "1.1"} (event_loop.py:83)
8/5/2020 11:37:16 AM2020-08-05 18:37:16 ERROR    Traceback (most recent call last):
8/5/2020 11:37:16 AM  File "/app/src/index_runner/event_loop.py", line 77, in start_loop
8/5/2020 11:37:16 AM    message_handler(msg)
8/5/2020 11:37:16 AM  File "/app/src/index_runner/main.py", line 40, in _handle_msg
8/5/2020 11:37:16 AM    es_indexer.run_indexer(obj, ws_info, msg)
8/5/2020 11:37:16 AM  File "/app/src/index_runner/es_indexer.py", line 68, in run_indexer
8/5/2020 11:37:16 AM    for data in index_obj(obj, ws_info, msg):
8/5/2020 11:37:16 AM  File "/app/src/index_runner/es_indexers/main.py", line 62, in index_obj
8/5/2020 11:37:16 AM    for indexer_ret in indexer(obj_data, ws_info, obj_data_v1):
8/5/2020 11:37:16 AM  File "/app/src/index_runner/es_indexers/sample_set.py", line 114, in index_sample_set
8/5/2020 11:37:16 AM    sample = _get_sample(samp)
8/5/2020 11:37:16 AM  File "/app/src/index_runner/es_indexers/sample_set.py", line 38, in _get_sample
8/5/2020 11:37:16 AM    raise RuntimeError(f"Returned from sample service with status {resp.status_code} - {resp.text}")
8/5/2020 11:37:16 AMRuntimeError: Returned from sample service with status 500 - {"error": {"code": -32000, "name": "Server error", "message": "Sample service error code 20000 Unauthorized: User jayrbolton cannot read sample cf679098-f431-4960-853f-d5df0590566f", "error": "Traceback (most recent call last):\n  File \"/kb/module/lib/SampleService/SampleServiceServer.py\", line 102, in _call_method\n    result = method(ctx, *params)\n  File \"/kb/module/lib/SampleService/SampleServiceImpl.py\", line 299, in get_sample\n    id_, _get_user_from_object(ctx, _CTX_USER), ver, as_admin=admin)\n  File \"/kb/module/lib/SampleService/core/samples.py\", line 179, in get_sample\n    self._check_perms(_not_falsy(id_, 'id_'), user, _SampleAccessType.READ, as_admin=as_admin)\n  File \"/kb/module/lib/SampleService/core/samples.py\", line 140, in _check_perms\n    raise _UnauthorizedError(errmsg)\nSampleService.core.errors.UnauthorizedError: Sample service error code 20000 Unauthorized: User jayrbolton cannot read sample cf679098-f431-4960-853f-d5df0590566f\n"}, "id": "", "version": "1.1"}
8/5/2020 11:37:16 AM (event_loop.py:84)
```

The reason it is citing user "jayrbolton" is because I am using an auth token generated from my account, which has RE and workspace admin privileges. I don't know how SampleService auth works, but apparently we need an auth token that can serve as a SampleService admin as well.

**Comment by jayrbolton** [comment]
Here is the actual event that triggered it:

```
{'wsid': 52886, 'ver': 1, 'perm': None, 'evtype': 'NEW_VERSION', 'objid': 6, 'time': 1596652482644, 'objtype': 'KBaseSets.SampleSet-2.0', 'permusers': [], 'user': 'slebras'} (event_loop.py:74)
```
