### ISSUE TITLE
SDK indexer not working on ExpressionMatrix

### ISSUE THREAD

**Issue by jayrbolton** [kbase/index_runner#90]
Got the following error on an event to index a `KBaseMatrices.ExpressionMatrix-3.2` object:

```
1/2/2020 3:30:21 PM================================================================================
1/2/2020 3:30:46 PMERROR:root:Error indexing:
1/2/2020 3:30:46 PM--------------------------------------------------------------------------------
1/2/2020 3:30:46 PM{'wsid': 45507, 'ver': 1, 'perm': None, 'evtype': 'NEW_VERSION', 'objid': 3, 'time': 1578007845935, 'objtype': 'KBaseMatrices.ExpressionMatrix-3.2', 'permusers': [], 'user': 'tgu2'}
1/2/2020 3:30:46 PM{'code': -32000, 'name': 'Server error', 'message': "'Module cannot be found based on module_name or git_url parameters.'", 'error': 'Traceback (most recent call last):\n  File "/kb/deployment/lib/biokbase/catalog/Server.py", line 101, in _call_method\n    result = method(ctx, *params)\n  File "/kb/deployment/lib/biokbase/catalog/Impl.py", line 674, in get_module_version\n    version = self.cc.get_module_version(selection)\n  File "/kb/deployment/lib/biokbase/catalog/controller.py", line 27, in wrapper\n    result = func(*args, **kwargs)\n  File "/kb/deployment/lib/biokbase/catalog/controller.py", line 523, in get_module_version\n    raise ValueError(\'Module cannot be found based on module_name or git_url parameters.\')\nValueError: Module cannot be found based on module_name or git_url parameters.\n'}
1/2/2020 3:30:46 PM--------------------------------------------------------------------------------
1/2/2020 3:30:46 PMTraceback (most recent call last):
1/2/2020 3:30:46 PM  File "/app/src/index_runner/es_indexer.py", line 55, in ws_event
1/2/2020 3:30:46 PM    self._run_indexer(msg)
1/2/2020 3:30:46 PM  File "/app/src/index_runner/es_indexer.py", line 97, in _run_indexer
1/2/2020 3:30:46 PM    for result in index_obj(msg):
1/2/2020 3:30:46 PM  File "/app/src/index_runner/es_indexers/main.py", line 83, in index_obj
1/2/2020 3:30:46 PM    for indexer_ret in indexer(obj_data, ws_info, obj_data_v1):
1/2/2020 3:30:46 PM  File "/app/src/index_runner/es_indexers/from_sdk.py", line 216, in index_from_sdk
1/2/2020 3:30:46 PM    image = _get_docker_image_name(sdk_app, sdk_version)
1/2/2020 3:30:46 PM  File "/app/src/index_runner/es_indexers/from_sdk.py", line 43, in _get_docker_image_name
1/2/2020 3:30:46 PM    raise RuntimeError(json_resp['error'])
1/2/2020 3:30:46 PMRuntimeError: {'code': -32000, 'name': 'Server error', 'message': "'Module cannot be found based on module_name or git_url parameters.'", 'error': 'Traceback (most recent call last):\n  File "/kb/deployment/lib/biokbase/catalog/Server.py", line 101, in _call_method\n    result = method(ctx, *params)\n  File "/kb/deployment/lib/biokbase/catalog/Impl.py", line 674, in get_module_version\n    version = self.cc.get_module_version(selection)\n  File "/kb/deployment/lib/biokbase/catalog/controller.py", line 27, in wrapper\n    result = func(*args, **kwargs)\n  File "/kb/deployment/lib/biokbase/catalog/controller.py", line 523, in get_module_version\n    raise ValueError(\'Module cannot be found based on module_name or git_url parameters.\')\nValueError: Module cannot be found based on module_name or git_url parameters.\n'}
1/2/2020 3:30:46 PM
1/2/2020 3:30:46 PM================================================================================
```

**Comment by jayrbolton** [comment]
I'm seeing this type is configured to use the app `kbasematrices_indexer.run_kbasematrices_indexer` but I dont' see this registered in the app catalog on CI.

**Comment by slebras** [comment]
Registered `kbasematrices_indexer` on CI. Haven't yet tested to confirm if this resolves issue

**Comment by jayrbolton** [comment]
:ok_man: :ok_hand: :ok:

**Comment by scanon** [comment]
Fixed
